# Generated by Django 5.0.6 on 2024-07-13 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0012_alter_colour_image_colour_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_products',
            name='Products_color_variant',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product_color_variant',
        ),
        migrations.AddField(
            model_name='cart_products',
            name='Products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.products'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.products'),
        ),
    ]
