# Generated by Django 5.0.6 on 2024-07-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_products_products_color_variant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_products',
            old_name='Products',
            new_name='products',
        ),
    ]
