# Generated by Django 5.0.6 on 2024-07-15 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_products_cart_products_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_products',
            old_name='products',
            new_name='Products',
        ),
    ]
