# Generated by Django 5.0.6 on 2024-07-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cart_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_products',
            old_name='Products',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='cart_products',
            name='sub_total',
        ),
    ]
