# Generated by Django 5.0.6 on 2024-07-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_products_cart_products_products_and_more'),
        ('products', '0014_remove_products_img_productimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_products',
            new_name='CartProducts',
        ),
    ]
