# Generated by Django 5.0.6 on 2024-08-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_coupon_usercoupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter discount percentage if applicable.', max_digits=5, null=True),
        ),
    ]
