# Generated by Django 5.0.6 on 2024-08-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_cart_coupon_cart_coupon_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_applied_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
