# Generated by Django 5.0.6 on 2024-08-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
