# Generated by Django 5.0.6 on 2024-08-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderproduct_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='request_status',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='return_status',
            field=models.CharField(default=False, max_length=30, null=True),
        ),
    ]
