# Generated by Django 5.0.6 on 2024-08-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_coupon_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Payment_failed', 'Payment_failed'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Pending', max_length=20, null=True),
        ),
    ]
