# Generated by Django 5.0.6 on 2024-08-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_orderproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='approvel',
            field=models.BooleanField(default=False),
        ),
    ]
