# Generated by Django 5.0.6 on 2024-06-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_slug',
            new_name='slug',
        ),
    ]
