# Generated by Django 5.0.6 on 2024-06-30 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='colour_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('img1', models.ImageField(null=True, upload_to='products/')),
                ('img2', models.ImageField(null=True, upload_to='products/')),
                ('img3', models.ImageField(null=True, upload_to='products/')),
                ('is_listed', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colour_variants', to='products.products')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
