# Generated by Django 5.0.6 on 2024-07-04 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_colour_product_img1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour_product',
            name='quantity',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
