# Generated by Django 5.0.6 on 2024-07-05 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_colour_image_colour_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour_image',
            name='colour_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.colour_product'),
        ),
    ]
