# Generated by Django 5.0.6 on 2024-07-13 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_products_products_color_variant_and_more'),
        ('products', '0012_alter_colour_image_colour_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colour_product',
            name='product',
        ),
        migrations.AddField(
            model_name='products',
            name='details',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Colour_image',
        ),
        migrations.DeleteModel(
            name='colour_product',
        ),
    ]
