# Generated by Django 5.0.6 on 2024-08-09 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_products_img_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='products',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_offer_applied',
            field=models.BooleanField(default=False),
        ),
    ]
