# Generated by Django 5.0.6 on 2024-08-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_products_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
