# Generated by Django 5.0.6 on 2024-08-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_products_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='validate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
