# Generated by Django 5.0.6 on 2024-08-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_rename_validate_products_validate_offerdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
