# Generated by Django 5.0.6 on 2024-06-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=60)),
                ('cat_thumbnail', models.ImageField(upload_to='Category')),
                ('is_listed', models.BooleanField(default=True)),
            ],
        ),
    ]
