# Generated by Django 5.0.6 on 2024-06-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
