# Generated by Django 5.0.6 on 2024-08-09 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='category',
            name='is_offer_applied',
            field=models.BooleanField(default=False),
        ),
    ]
