# Generated by Django 5.0.6 on 2024-07-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
    ]
