# Generated by Django 5.0.6 on 2024-07-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_remove_address_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.IntegerField(default=1111111111, max_length=10),
            preserve_default=False,
        ),
    ]
