# Generated by Django 5.0.6 on 2024-07-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0009_alter_address_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default=2, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
